services:
  backend:
    image: vps-management-backend
    ports:
      - "3001:3001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - "969"
  frontend:
    image: vps-management-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
